name: Package 
on: [push, workflow_dispatch]

env:
  COMPANION_REF: 'v2.3.1'

jobs:
  win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'bitfocus/companion'
          ref: ${{ env.COMPANION_REF }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build
        shell: bash
        run: |
          yarn config set network-timeout 100000 -g
          yarn config set script-shell bash
          yarn update
          yarn add companion-module-presonus-studiolive@$GITHUB_REPOSITORY#$GITHUB_SHA
          yarn run windist
          7z.exe a companion-win-x64.7z ./electron-output/win-unpacked/*
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win64
          path: companion-win-x64.7z

  osx:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'bitfocus/companion'
          ref: ${{ env.COMPANION_REF }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build
        shell: bash
        run: |
          yarn config set network-timeout 100000 -g
          yarn update
          yarn add companion-module-presonus-studiolive@$GITHUB_REPOSITORY#$GITHUB_SHA
          yarn run macdist
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: electron-output/companion-mac-x64.dmg

  osx-arm64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'bitfocus/companion'
          ref: ${{ env.COMPANION_REF }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build
        shell: bash
        run: |
          yarn config set network-timeout 100000 -g
          yarn update
          yarn add companion-module-presonus-studiolive@$GITHUB_REPOSITORY#$GITHUB_SHA
          yarn run macarmdist
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64
          path: electron-output/companion-mac-arm64.dmg

  linux64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'bitfocus/companion'
          ref: ${{ env.COMPANION_REF }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build
        shell: bash
        run: |
          yarn config set network-timeout 100000 -g
          yarn update
          yarn add companion-module-presonus-studiolive@$GITHUB_REPOSITORY#$GITHUB_SHA
          yarn run lindist
          cd electron-output
          mv linux-unpacked companion-x64
          tar -cvzf companion-linux-x64.tar.gz companion-x64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: electron-output/companion-linux-x64.tar.gz